# Generated by Django 5.1 on 2024-12-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_alter_ride_ride_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Actual_Pon',
            field=models.ManyToManyField(related_name='passengers', to='register.ride'),
        ),
    ]
