# Generated by Django 5.1 on 2024-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_user_actual_pon'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='Status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Finished', 'Finished'), ('Paid', 'Paid')], default='Waiting', max_length=20),
        ),
    ]
