# Generated by Django 5.1 on 2024-12-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_active',
            field=models.BooleanField(default=False, help_text='Indica si el conductor está activo.'),
        ),
    ]
