# Generated by Django 5.1 on 2024-12-05 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Actual_Pon',
        ),
        migrations.AddField(
            model_name='user',
            name='Actual_Pon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Actual_pon', to='register.ride'),
        ),
    ]
