# Generated by Django 5.1 on 2024-12-06 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_remove_user_actual_pon_user_actual_pon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Actual_Pon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Actual_pon', to='register.ride'),
        ),
    ]
