# Generated by Django 5.1 on 2024-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_alter_user_actual_pon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='Date_End',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
