# Generated by Django 5.1 on 2024-12-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_alter_ride_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Rate',
            field=models.FloatField(default=0.0, help_text='Rating of the driver from 0.0 to 5.0'),
        ),
        migrations.AddField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_driver', to='register.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments_as_passenger', to='register.user'),
        ),
    ]
