# Generated by Django 5.1 on 2024-12-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_payment_rate_payment_comment_alter_payment_driver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Status',
        ),
        migrations.AddField(
            model_name='user',
            name='Car_Brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Car_Model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Car_Year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
