# Generated by Django 5.1 on 2024-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_remove_user_status_user_car_brand_user_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='License_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
